# docker compose -f docker/mysql.yaml up -d
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306" # Maps container port 3306 to host port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --require_secure_transport=OFF
